dist: trusty
sudo: false
language: node_js
cache:
  directories:
    - ~/.npm
notifications:
  email: false
before_install:
  - npm i -g npm@latest
deploy:
  provider: script
  script: npm run travis-deploy-once "npm run semantic-release"
  on:
    branch: master
